// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ListDnd': string;
  'content': string;
}
export const cssExports: CssExports;
export default cssExports;
