// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBlockBox': string;
  'addBlockContainer': string;
  'content': string;
  'dndItem': string;
  'left': string;
  'loadingMask': string;
  'mainBox': string;
  'myDndComponent': string;
  'text': string;
  'topBar': string;
}
export const cssExports: CssExports;
export default cssExports;
