// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'leftContent': string;
  'projectHeader': string;
  'projectInfo': string;
  'tabs': string;
  'thumbnail': string;
  'vertical': string;
}
export const cssExports: CssExports;
export default cssExports;
