// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBlockBox': string;
  'addBlockContainer': string;
  'addItemBtn': string;
  'block': string;
  'blockBox': string;
  'blockTitle': string;
  'blockTitleBox': string;
  'content': string;
  'itemlist': string;
  'left': string;
  'loadingMask': string;
  'mainBox': string;
  'menuBox': string;
  'menuItem': string;
  'moreBtn': string;
  'myDndComponent': string;
  'noSortDragMask': string;
  'text': string;
  'topBar': string;
}
export const cssExports: CssExports;
export default cssExports;
