// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hideMenuHead': string;
  'layout': string;
  'noStylePage': string;
  'projectPage': string;
}
export const cssExports: CssExports;
export default cssExports;
